# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install pycodestyle

before_script:
  -  pycodestyle --exclude ./buildroot,tests,.git,build .

script:
  - python setup.py test
