# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

install:
  - pip install anteater --no-cache-dir

before_script:
  - git diff --name-only HEAD^ > ./patch
  - anteater --version

script:
  - anteater --ips --urls --binaries --project CHANGEME! --patchset ./patch
