projects:
    - inspector
    - doctor
    - Compliance
    - apex
    - armband
    - availability
    - bottlenecks
    - compass4nfv
    - conductor
    - copper
    - cperf
    - doctor
    - domino
    - dovetail
    - dpacc
    - enfv
    - escalator
    - fastpathmetrics
    - fds
    - fuel
    - functest
    - genesis
    - genesisreq
    - inspector
    - ipv6
    - joid
    - kvmfornfv
    - lsoapi
    - models
    - moon
    - movie
    - multisite
    - netready
    - octopus
    - onosfw
    - oscar
    - ovno
    - ovsnfv
    - parser
    - pharos
    - pinpoint
    - policytest
    - prediction
    - promise
    - qtip
    - releng
    - rs
    - sandbox
    - sdnvpn
    - securedlab
    - sfc
    - storperf
    - vnf_forwarding_graph
    - vswitchperf
    - yardstick
