bad_hashes:
    - HAVAL-128
    - GOST
    - MD2
    - MD4
    - MD5
    - DES
    - RC4
    - SHA-0
    - SHA-1
    - STREEBOG
    - DUAL_EC_DRBG
    - SNEFRU
    - PANAMA
    - RIPEMD

bad_tls:
    - SSLV1
    - SSLV2
    - TLSV1
    - TLSV1.1
